spring:
  datasource:
    url: jdbc:mysql://yesterpay.cxuywiqu0fpy.ap-northeast-2.rds.amazonaws.com:3306/yesterpay
    username: kb2024
    password: kbkb1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

#log4j ?? / ?? ??
logging:
  config=classpath:log4j2.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true